#include "stm32f1xx_hal.h"


#define LED_BAT_PIN GPIO_PIN_7							// port A
#define BUZZER_PIN  GPIO_PIN_15							// port A
#define COM_ENABLE_PIN  GPIO_PIN_8					// port A

#define LED_24V_PIN GPIO_PIN_7							// port B
#define LED_12V_PIN GPIO_PIN_0							// port B
#define LED_PRNT_PIN GPIO_PIN_1							// port B
#define LED_CHRG_PIN GPIO_PIN_2							// port B
#define LED_36V_PIN GPIO_PIN_10							// port B

#define LED_BATLEVEL_3_3_PIN GPIO_PIN_11		// port B
#define LED_BATLEVEL_2_3_PIN GPIO_PIN_12		// port B
#define LED_BATLEVEL_1_3_PIN GPIO_PIN_14		// port B
#define LED_HEARTBEAT_PIN GPIO_PIN_15				// port B
#define CHARGE_ENABLE_PIN GPIO_PIN_5				// port B
#define V24_ENABLE_PIN GPIO_PIN_4						// port B
#define BAT_ENABLE_PIN GPIO_PIN_3						// port B
#define LED_19V_PIN GPIO_PIN_6				      // port B
#define USB_PULLUP_PIN GPIO_PIN_9				    // port B

#define LED_EXT_PIN GPIO_PIN_15				      // port C
#define BUT_PIN  GPIO_PIN_14							  // port C

#define LED_CHRG(x) ((x)? (HAL_GPIO_WritePin(GPIOB,LED_CHRG_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_CHRG_PIN,GPIO_PIN_RESET)));
#define LED_BAT(x) ((x)? 	(HAL_GPIO_WritePin(GPIOA,LED_BAT_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOA,LED_BAT_PIN,GPIO_PIN_RESET)));
#define LED_PRNT(x) ((x)? (HAL_GPIO_WritePin(GPIOB,LED_PRNT_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_PRNT_PIN,GPIO_PIN_RESET)));
#define LED_12V(x) ((x)? 	(HAL_GPIO_WritePin(GPIOB,LED_12V_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_12V_PIN,GPIO_PIN_RESET)));
#define LED_24V(x) ((x)? 	(HAL_GPIO_WritePin(GPIOB,LED_24V_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_24V_PIN,GPIO_PIN_RESET)));
#define LED_36V(x) ((x)? 	(HAL_GPIO_WritePin(GPIOB,LED_36V_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_36V_PIN,GPIO_PIN_RESET)));
#define LED_EXT(x) ((x)? 	(HAL_GPIO_WritePin(GPIOC,LED_EXT_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOC,LED_EXT_PIN,GPIO_PIN_RESET)));
#define LED_19V(x) ((x)? 	(HAL_GPIO_WritePin(GPIOB,LED_19V_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_19V_PIN,GPIO_PIN_RESET)));

#define LED_BAT_1(x) ((x)? (HAL_GPIO_WritePin(GPIOB,LED_BATLEVEL_1_3_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_BATLEVEL_1_3_PIN,GPIO_PIN_RESET)));
#define LED_BAT_2(x) ((x)? (HAL_GPIO_WritePin(GPIOB,LED_BATLEVEL_2_3_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_BATLEVEL_2_3_PIN,GPIO_PIN_RESET)));
#define LED_BAT_3(x) ((x)? (HAL_GPIO_WritePin(GPIOB,LED_BATLEVEL_3_3_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_BATLEVEL_3_3_PIN,GPIO_PIN_RESET)));

#define LED_HEARTBEAT(x) 	((x)? (HAL_GPIO_WritePin(GPIOB,LED_HEARTBEAT_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,LED_HEARTBEAT_PIN,GPIO_PIN_RESET)));
#define V24_ENABLE(x)    	((x)? (HAL_GPIO_WritePin(GPIOB,V24_ENABLE_PIN,GPIO_PIN_RESET)):(HAL_GPIO_WritePin(GPIOB,V24_ENABLE_PIN,GPIO_PIN_SET)));
#define BAT_ENABLE(x)    	((x)? (HAL_GPIO_WritePin(GPIOB,BAT_ENABLE_PIN,GPIO_PIN_RESET)):(HAL_GPIO_WritePin(GPIOB,BAT_ENABLE_PIN,GPIO_PIN_SET)));
#define CHARGE_ENABLE(x) 	((x)? (HAL_GPIO_WritePin(GPIOB,CHARGE_ENABLE_PIN,GPIO_PIN_RESET)):(HAL_GPIO_WritePin(GPIOB,CHARGE_ENABLE_PIN,GPIO_PIN_SET)));
#define COM_ENABLE(x) 		((x)? (HAL_GPIO_WritePin(GPIOA,COM_ENABLE_PIN,GPIO_PIN_RESET)):(HAL_GPIO_WritePin(GPIOA,COM_ENABLE_PIN,GPIO_PIN_SET)));
#define USB_PULLUP(x) 		((x)? (HAL_GPIO_WritePin(GPIOB,USB_PULLUP_PIN,GPIO_PIN_SET)):(HAL_GPIO_WritePin(GPIOB,USB_PULLUP_PIN,GPIO_PIN_RESET)));

#define ADC_30V_PIN GPIO_PIN_0			
#define ADC_BAT_PIN GPIO_PIN_1	
#define ADC_24V_PIN GPIO_PIN_2	
#define ADC_23V_PIN GPIO_PIN_3	
#define ADC_12V_PIN GPIO_PIN_4	
#define ADC_36V_PIN GPIO_PIN_5
#define ADC_19V_PIN GPIO_PIN_6

#define BUT HAL_GPIO_ReadPin(GPIOC,BUT_PIN)  //PC14

#define OFF 0
#define ON 1

/*
void V24_ENABLE(int onOff);
void BAT_ENABLE(int onOff);
*/
