#include "gpio.h"
#include "pins.h"
#include "timer.h"


void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
	__HAL_RCC_ADC1_CLK_ENABLE();

  HAL_GPIO_WritePin(GPIOA, LED_BAT_PIN|BUZZER_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(GPIOB, LED_19V_PIN|LED_24V_PIN|LED_12V_PIN|LED_PRNT_PIN|LED_CHRG_PIN|LED_36V_PIN|LED_BATLEVEL_3_3_PIN|LED_BATLEVEL_2_3_PIN|LED_BATLEVEL_1_3_PIN|LED_HEARTBEAT_PIN|V24_ENABLE_PIN|BAT_ENABLE_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIOB, USB_PULLUP_PIN|V24_ENABLE_PIN|BAT_ENABLE_PIN|CHARGE_ENABLE_PIN, GPIO_PIN_SET);
	
  GPIO_InitStruct.Pin = LED_BAT_PIN|BUZZER_PIN|COM_ENABLE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
	
	GPIO_InitStruct.Pin = USB_PULLUP_PIN|LED_19V_PIN|LED_24V_PIN|LED_12V_PIN|LED_PRNT_PIN|LED_CHRG_PIN|LED_36V_PIN|LED_BATLEVEL_3_3_PIN|LED_BATLEVEL_2_3_PIN|LED_BATLEVEL_1_3_PIN|LED_HEARTBEAT_PIN|CHARGE_ENABLE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
	
	GPIO_InitStruct.Pin = LED_EXT_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
	
	GPIO_InitStruct.Pin = V24_ENABLE_PIN|BAT_ENABLE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
	

	//ADC1 GPIO Configuration    
	GPIO_InitStruct.Pin = ADC_30V_PIN|ADC_BAT_PIN|ADC_24V_PIN|ADC_23V_PIN|ADC_12V_PIN|ADC_36V_PIN|ADC_19V_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
	HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
	
	//BUT PC14
	GPIO_InitStruct.Pin = BUT_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}

/*
void V24_ENABLE(int onOff)
{
	if(onOff==ON) {
		_BAT_ENABLE(OFF);
		delay_us(100);
		_V24_ENABLE(ON);
	}
	else {
		_V24_ENABLE(OFF);
	}
}


void BAT_ENABLE(int onOff)
{
	if(onOff==ON) {
		_V24_ENABLE(OFF);
		delay_us(100);
		_BAT_ENABLE(ON);
	}
	else {
		_BAT_ENABLE(OFF);
	}
}*/

